### ISSUE TITLE
Feature Request: ACE Arsenal

### ISSUE THREAD

**Issue by dedmen** [Xeno69/Domination#1]
Features: https://github.com/acemod/ACE3/pull/5734
Stats: https://github.com/acemod/ACE3/pull/6110
https://ace3mod.com/wiki/feature/arsenal.html
https://ace3mod.com/wiki/framework/arsenal-framework.html

Full arsenal is easy to implement
https://github.com/Xeno69/Domination/blob/cdaa46cac2e3de38fbab02404f9c324f2534a52e/co30_Domination.Altis/x_client/x_f/fn_inventoryopened.sqf#L14
->
`[player, player, true] call ace_arsenal_fnc_openBox`

The limited arsenal variant is slightly different. ACE Arsenal takes array of all Classnames without categorization. I think BI arsenal does things differently in that regard.

If ACE Arsenal is used then
https://github.com/Xeno69/Domination/blob/cdaa46cac2e3de38fbab02404f9c324f2534a52e/co30_Domination.Altis/x_client/x_setupplayer.sqf#L899
is not needed.
and
https://github.com/Xeno69/Domination/blob/cdaa46cac2e3de38fbab02404f9c324f2534a52e/co30_Domination.Altis/x_client/x_f/x_ui/fn_recruitbuttonaction.sqf#L150
should also be replaced.

**Comment by dedmen** [comment]
>The limited arsenal variant is slightly different. ACE Arsenal takes array of all Classnames without categorization. I think BI arsenal does things differently in that regard.

You should pass the array of classnames to ACE arsenal when opening the limited variant.
You definitely should not modify a static variable that is computed at gameStart.

**Comment by Xeno69** [comment]
First of all, uiNamespace variables are getting recreated each time a player connects to a server (because of security concerns, was changed during A2/OA times).

Second, BI does it correctly and puts the virtual arsenal classes into a variable in mission namespace (ace does the same just not mission namespace).
It is never a good idea to just hope that third party uses do not change those public variables.

**Comment by dedmen** [comment]
>First of all, uiNamespace variables are getting recreated each time a player connects to a server (because of security concerns, was changed during A2/OA times).

Nope. Not at all. missionNamespace yes. But none of the other namespaces.

>Second, BI does it correctly and puts the virtual arsenal classes into a variable in mission namespace (ace does the same just not mission namespace).

ACE arsenal does it so it doesn't have to rescan items each mission restart.
The ACE thing is completly different. It's a list of all existing Items in config. Selecting which items should be displayed is done later.

**Comment by Xeno69** [comment]
Believe me, uiNamespace gets deleted when a player connects to a server otherwise one could change whatever he likes in uiNamespace in the single player editor, change scripts or whatever and do nasty things once connected.

It was a major security issue during OA times and BI changed it back then. 

Compilefinal is also not a solution. 
The extDB3 author added a compileFinal to the only public variable the mod has and broke all missions using it because it was no longer a boolean variable but code.

Anyway, if there is an easier solution to clean the ace arsenal array let me know.

Best solution would be to make the variable a normal mission namespace variable, that would only be filled if needed once per mission.

**Comment by dedmen** [comment]
>The extDB3 author added a compileFinal to the only public variable the mod has and broke all missions using it because it was no longer a boolean variable but code.

Not a concern. no-one should be accessing that variable.


>Believe me, uiNamespace gets deleted when a player connects to a server

I will believe you if you tell me why ACE arsenal works at all if the variable that only get's created once at gameStart get's deleted before being accessed.

**Comment by commy2** [comment]
>Believe me, uiNamespace gets deleted when a player connects to a server otherwise one could change whatever he likes in uiNamespace in the single player editor, change scripts or whatever and do nasty things once connected.

This is demonstrably wrong. In fact, this not being the case is the only reason `compileFinal` exists: to cache the functions library in ui namespace while at the same time be unable to inject arbitrary code.
