### ISSUE TITLE
Overflow - Spamm in Console

### ISSUE THREAD

**Issue by sunnus01** [Xeno69/Domination#137]
Hi having weird issue, cant host server normally, coz after like 8-9 hours i get in console:
Overflow
Overflow
Overflow
Overflow
Overflow
and so on...
Massive LAG, Server FPS 0
Mission unplayable...
After server restart it's ok.
I notice that it happens when in game sun starts to set.

**Comment by Xeno69** [comment]
Well, that's something you should report to BI :)

Anyway, which version, which addons/mods are you using? Server RPT file?

**Comment by longtimegamer** [comment]
@sunnus01 Are you using a Linux server?  That was a chronic problem for the linux builds and I never found a solution.

**Comment by Xeno69** [comment]
@longtimegamer 
Then you really should report it to BI

**Comment by longtimegamer** [comment]
@Xeno69 As I remember, the issue was reported in the old BI tracker and I "voted" for it.  I think this issue has been reported (twice) and has been imported into the new issue tracker:

https://feedback.bistudio.com/T83321
https://feedback.bistudio.com/T80902

Both were created in 2015...  The problem disappeared on Windows so I switched, shame on me.  :)

**Comment by sunnus01** [comment]
Yeah it's Linux CentOS 7, and now i get it... Just gonna switch to WIN server

**Comment by Xeno69** [comment]
Closing this one :)

**Comment by longtimegamer** [comment]
I created a new issue in the BI tracker.  The old issues didn't seem to communicate the problem exists only for linux.

https://feedback.bistudio.com/T150649

If there is follow-up from BI then I will happily support troubleshooting.  Not very likely.
